USE [BALTA]
GO

CREATE TABLE [STUDENT]
(
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [NAME] NVARCHAR(120) NOT NULL,
    [EMAIL] NVARCHAR(180) NOT NULL,
    [DOCUMENT] NVARCHAR(20) NULL,
    [PHONE] NVARCHAR(20) NULL,
    [BIRTHDATE] DATETIME NULL,
    [CREATEDATE] DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT [PK_STUDENT] PRIMARY KEY ([ID])
);
GO

CREATE TABLE AUTHOR
(
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [NAME] NVARCHAR(80) NOT NULL,
    [TITLE] NVARCHAR(80) NOT NULL,
    [IMAGE] NVARCHAR(1024) NOT NULL,
    [BIO] NVARCHAR(2000) NOT NULL,
    [URL] NVARCHAR(450) NOT NULL,
    [EMAIL] NVARCHAR(160) NOT NULL,
    [TYPE] TINYINT NOT NULL, -- 0 A 255
    CONSTRAINT PK_AUTHOR PRIMARY KEY ([ID])
);
GO

CREATE TABLE CAREER
(
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [TITLE] NVARCHAR(80) NOT NULL,
    [SUMMARY] NVARCHAR(2000) NOT NULL,
    [DURATIONINMINUTES] INT NOT NULL,
    [ACTIVE] BIT NOT NULL,
    [FEATURED] BIT NOT NULL,
    TAGS NVARCHAR(160) NOT NULL,
    CONSTRAINT PK_CAREER PRIMARY KEY ([ID])
)
GO

CREATE TABLE CATEGORY
(
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [TITLE] NVARCHAR(160) NOT NULL,
    [URL] NVARCHAR(1024) NOT NULL,
    [SUMMARY] NVARCHAR(2000) NOT NULL,
    [ORDER] INT NOT NULL,
    [DESCRIPTION] TEXT NOT NULL,
    [FEATURED] BIT NOT NULL,

    CONSTRAINT PK_CATEGORY PRIMARY KEY ([ID])
);
GO

CREATE TABLE [COURSE]
(
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [TAG] NVARCHAR(20) NOT NULL,
    [TITLE] NVARCHAR(160) NOT NULL,
    [SUMMARY] NVARCHAR(2000) NOT NULL,
    [URL] NVARCHAR(1024) NOT NULL,
    [LEVEL] TINYINT NOT NULL,
    [DURATIONINMINUTES] INT NOT NULL,
    [CREATEDATE] DATETIME NOT NULL,
    [LASTUPDATEDATE] DATETIME NOT NULL,
    [ACTIVE] BIT NOT NULL,
    [FREE] BIT NOT NULL,
    [FEATURED] BIT NOT NULL,
    [AUTHORID] UNIQUEIDENTIFIER NOT NULL,
    [CATEGORYID] UNIQUEIDENTIFIER NOT NULL,
    [TAGS] NVARCHAR(160) NOT NULL,
    CONSTRAINT [PK_COURSE] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_COURSE_AUTHOR_AUTHORID] FOREIGN KEY ([AUTHORID]) REFERENCES [AUTHOR] ([ID]),
    CONSTRAINT [FK_COURSE_CATEGORY_CATEGORYID] FOREIGN KEY ([CATEGORYID]) REFERENCES [CATEGORY] ([ID])
);
GO

CREATE TABLE [CAREERITEM]
(
    [CAREERID] UNIQUEIDENTIFIER NOT NULL,
    [COURSEID] UNIQUEIDENTIFIER NOT NULL,
    [TITLE] NVARCHAR(160) NOT NULL,
    [DESCRIPTION] TEXT NOT NULL,
    [ORDER] TINYINT NOT NULL,
    
    CONSTRAINT [PK_CAREERITEM] PRIMARY KEY ([COURSEID], [CAREERID]),
    CONSTRAINT [FK_CAREERITEM_CAREER_CAREERID] FOREIGN KEY ([CAREERID]) REFERENCES [CAREER] ([ID]),
    CONSTRAINT [FK_CAREERITEM_COURSE_COURSEID] FOREIGN KEY ([COURSEID]) REFERENCES [COURSE] ([ID])
);
GO

CREATE TABLE [STUDENTCOURSE]
(
    [COURSEID] UNIQUEIDENTIFIER NOT NULL,
    [STUDENTID] UNIQUEIDENTIFIER NOT NULL,
    [PROGRESS] TINYINT NOT NULL,
    [FAVORITE] BIT NOT NULL,
    [STARTDATE] DATETIME NOT NULL,
    [LASTUPDATEDATE] DATETIME NULL DEFAULT(GETDATE()),
    CONSTRAINT [PK_STUDENTCOURSE] PRIMARY KEY ([COURSEID], [STUDENTID]),
    CONSTRAINT [FK_STUDENTCOURSE_COURSE_COURSEID] FOREIGN KEY ([COURSEID]) REFERENCES [COURSE] ([ID]),
    CONSTRAINT [FK_STUDENTCOURSE_STUDENT_STUDENTID] FOREIGN KEY ([STUDENTID]) REFERENCES [STUDENT] ([ID])
);
GO