DROP TABLE [CURSO]
DROP TABLE [CATEGORIA]

CREATE TABLE [CATEGORIA]
(
    [ID] INT NOT NULL IDENTITY(1, 1),
    [NOME] NVARCHAR(80) NOT NULL,

    CONSTRAINT [PK_CATEGORIA] PRIMARY KEY([ID])
)

GO


CREATE TABLE [CURSO]
(
    [ID] INT NOT NULL IDENTITY(1, 1),
    [NOME] NVARCHAR(80) NOT NULL,
    [CATEGORIAID] INT NOT NULL,

    CONSTRAINT [PK_CURSO] PRIMARY KEY([ID]),
    CONSTRAINT [FK_CURSO_CATEGORIA] FOREIGN KEY([CATEGORIAID])
        REFERENCES [CATEGORIA] ([ID])

)
GO

