INSERT INTO [CATEGORIA] ([NOME]) VALUES('BACKEND')
INSERT INTO [CATEGORIA] ([NOME]) VALUES('FRONTEND')
INSERT INTO [CATEGORIA] ([NOME]) VALUES('MOBILE')

INSERT INTO [CURSO] ([NOME],[CATEGORIAID]) VALUES ('FUNDAMENTOS C#', 1)
INSERT INTO [CURSO] ([NOME],[CATEGORIAID]) VALUES ('FUNDAMENTOS OOP', 1)
INSERT INTO [CURSO] ([NOME],[CATEGORIAID]) VALUES ('FUNDAMENTOS OOP', 2)
INSERT INTO [CURSO] ([NOME],[CATEGORIAID]) VALUES ('FLUTTER', 3)

INSERT INTO [CURSO] VALUES('FLUTTER E SQLITE', 3)